/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graficos;
import Entidades.*;
import DBManager.*;
import java.awt.Image;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author DANIEL
 */
public class Principal extends javax.swing.JFrame {
    private Usuario actual;
    private ResultSet consulta;
    
    /**
     * Creates new form Principal
     */
    public Principal() {        
        initComponents();
        incorrectValuesLbl.setVisible(false);
        usrShowPassBtn.setIcon(new ImageIcon(((new ImageIcon(getClass().getResource("/Graficos/eye.png"))).getImage().getScaledInstance(usrShowPassBtn.getWidth(), usrShowPassBtn.getHeight(), Image.SCALE_SMOOTH))));
        signOut();
        connectionManager.connect();
    }

    public void clearLogIn(){
        logInUsrTxt.setText("");
        LogInPassTxt.setText("");
        incorrectValuesLbl.setVisible(false);
    }
    
    public void signOut(){
        logInFrame.setVisible(true);
        menuAdministradorFile.setVisible(false);
        menuOperadoresFile.setVisible(false);
        menuRecepcionistaFile.setVisible(false);
        menuAdministradorFile.setEnabled(false);
        menuOperadoresFile.setEnabled(false);
        menuRecepcionistaFile.setEnabled(false);
        frameCliente.doDefaultCloseAction();
        frameUsuario.doDefaultCloseAction();
        framePaquete.doDefaultCloseAction();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        logInFrame = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        logInUsrTxt = new javax.swing.JTextField();
        LogInPassTxt = new javax.swing.JPasswordField();
        logInBtn = new javax.swing.JButton();
        incorrectValuesLbl = new javax.swing.JLabel();
        frameCliente = new javax.swing.JInternalFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        clientNameTxt = new javax.swing.JTextField();
        clientNitTxt = new javax.swing.JTextField();
        clientSearchBtn = new javax.swing.JButton();
        clientSaveBtn = new javax.swing.JButton();
        frameUsuario = new javax.swing.JInternalFrame();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        usrPassTxt = new javax.swing.JPasswordField();
        usrShowPassBtn = new javax.swing.JToggleButton();
        usrUsrTxt = new javax.swing.JTextField();
        usrNameTxt = new javax.swing.JTextField();
        usrTypeCombo = new javax.swing.JComboBox<>();
        usrSaveBtn = new javax.swing.JButton();
        usrSearchBtn = new javax.swing.JButton();
        framePaquete = new javax.swing.JInternalFrame();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        paqueteNitTxt = new javax.swing.JTextField();
        paquetePesoTxt = new javax.swing.JFormattedTextField();
        paquetePriorizadoCheck = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        paquetePaquetesCombo = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAdministradorFile = new javax.swing.JMenu();
        administradorMenuModificar = new javax.swing.JMenu();
        administradorMenuUsuario = new javax.swing.JMenuItem();
        administradorMenuRuta = new javax.swing.JMenuItem();
        administradorMenuPC = new javax.swing.JMenuItem();
        menuOperadoresFile = new javax.swing.JMenu();
        operadorMenuModificar = new javax.swing.JMenu();
        operadorMenuAlmacen = new javax.swing.JMenuItem();
        menuRecepcionistaFile = new javax.swing.JMenu();
        recepcionistaMenModificar = new javax.swing.JMenu();
        recepcionistaMenuCliente = new javax.swing.JMenuItem();
        recepcionistaMenuEnvio = new javax.swing.JMenuItem();
        sesionMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jDesktopPane1.setMaximumSize(getMaximumSize());

        logInFrame.setClosable(true);
        logInFrame.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        logInFrame.setIconifiable(true);
        logInFrame.setTitle("Log In");
        logInFrame.setPreferredSize(new java.awt.Dimension(215, 310));
        logInFrame.setVisible(true);

        jLabel1.setText("Usuario:");

        jLabel2.setText("Contraseña:");

        logInBtn.setText("Ingresar");
        logInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInBtnActionPerformed(evt);
            }
        });

        incorrectValuesLbl.setForeground(new java.awt.Color(204, 0, 0));
        incorrectValuesLbl.setText("Usuario/Contraseña Incorrecto");

        javax.swing.GroupLayout logInFrameLayout = new javax.swing.GroupLayout(logInFrame.getContentPane());
        logInFrame.getContentPane().setLayout(logInFrameLayout);
        logInFrameLayout.setHorizontalGroup(
            logInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logInFrameLayout.createSequentialGroup()
                .addGroup(logInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(logInFrameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(logInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(15, 15, 15)
                        .addGroup(logInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LogInPassTxt)
                            .addComponent(logInUsrTxt)))
                    .addGroup(logInFrameLayout.createSequentialGroup()
                        .addGroup(logInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(logInFrameLayout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(logInBtn))
                            .addGroup(logInFrameLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(incorrectValuesLbl)))
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addContainerGap())
        );
        logInFrameLayout.setVerticalGroup(
            logInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logInFrameLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(incorrectValuesLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(logInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(logInUsrTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(logInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(LogInPassTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(logInBtn)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        frameCliente.setClosable(true);
        frameCliente.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        frameCliente.setIconifiable(true);
        frameCliente.setTitle("Clientes");
        frameCliente.setMinimumSize(new java.awt.Dimension(395, 206));
        frameCliente.setVisible(true);

        jLabel3.setText("Nombre");

        jLabel4.setText("NIT");

        clientSearchBtn.setText("Buscar");

        clientSaveBtn.setText("Guardar");
        clientSaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientSaveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(clientNameTxt)
                            .addComponent(clientNitTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(clientSearchBtn))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(clientSaveBtn)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(clientNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(clientNitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clientSearchBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(clientSaveBtn)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout frameClienteLayout = new javax.swing.GroupLayout(frameCliente.getContentPane());
        frameCliente.getContentPane().setLayout(frameClienteLayout);
        frameClienteLayout.setHorizontalGroup(
            frameClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        frameClienteLayout.setVerticalGroup(
            frameClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        frameUsuario.setClosable(true);
        frameUsuario.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        frameUsuario.setIconifiable(true);
        frameUsuario.setTitle("Usuario");
        frameUsuario.setVisible(true);

        jLabel5.setText("Usuario");

        jLabel6.setText("Nombre");

        jLabel7.setText("Contraseña");

        jLabel8.setText("Tipo");

        usrShowPassBtn.setPreferredSize(new java.awt.Dimension(20, 20));
        usrShowPassBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usrShowPassBtnActionPerformed(evt);
            }
        });

        usrTypeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Operador", "Recepcionista" }));

        usrSaveBtn.setText("Guardar");
        usrSaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usrSaveBtnActionPerformed(evt);
            }
        });

        usrSearchBtn.setText("Buscar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(usrSaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usrPassTxt)
                            .addComponent(usrUsrTxt)
                            .addComponent(usrNameTxt)
                            .addComponent(usrTypeCombo, 0, 130, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usrShowPassBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usrSearchBtn))
                .addGap(67, 67, 67))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(usrUsrTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usrSearchBtn))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(usrNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(usrPassTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(usrShowPassBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(usrTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(usrSaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout frameUsuarioLayout = new javax.swing.GroupLayout(frameUsuario.getContentPane());
        frameUsuario.getContentPane().setLayout(frameUsuarioLayout);
        frameUsuarioLayout.setHorizontalGroup(
            frameUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        frameUsuarioLayout.setVerticalGroup(
            frameUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        framePaquete.setClosable(true);
        framePaquete.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        framePaquete.setIconifiable(true);
        framePaquete.setTitle("Paquetes");
        framePaquete.setToolTipText("");
        framePaquete.setVisible(true);

        jLabel9.setText("Nit");

        jLabel10.setText("Peso");

        jLabel11.setText("Priorización");

        paquetePesoTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        jLabel12.setText("Codigo");

        jButton1.setText("Guardar");

        paquetePaquetesCombo.setEditable(true);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(paqueteNitTxt)
                            .addComponent(paquetePesoTxt)
                            .addComponent(paquetePaquetesCombo, 0, 142, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(paquetePriorizadoCheck))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(paquetePaquetesCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(paqueteNitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(paquetePesoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(paquetePriorizadoCheck))
                .addGap(34, 34, 34)
                .addComponent(jButton1)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout framePaqueteLayout = new javax.swing.GroupLayout(framePaquete.getContentPane());
        framePaquete.getContentPane().setLayout(framePaqueteLayout);
        framePaqueteLayout.setHorizontalGroup(
            framePaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(framePaqueteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        framePaqueteLayout.setVerticalGroup(
            framePaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(framePaqueteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jDesktopPane1.setLayer(logInFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(frameCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(frameUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(framePaquete, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(framePaquete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(logInFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(frameUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(frameCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(logInFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(frameUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(framePaquete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(frameCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        menuAdministradorFile.setText("Archivo");

        administradorMenuModificar.setText("Modificar");

        administradorMenuUsuario.setText("Usuario");
        administradorMenuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                administradorMenuUsuarioActionPerformed(evt);
            }
        });
        administradorMenuModificar.add(administradorMenuUsuario);

        administradorMenuRuta.setText("Ruta");
        administradorMenuModificar.add(administradorMenuRuta);

        administradorMenuPC.setText("Punto De Control");
        administradorMenuModificar.add(administradorMenuPC);

        menuAdministradorFile.add(administradorMenuModificar);

        jMenuBar1.add(menuAdministradorFile);

        menuOperadoresFile.setText("Archivo");

        operadorMenuModificar.setText("Modificar");

        operadorMenuAlmacen.setText("Almacen");
        operadorMenuModificar.add(operadorMenuAlmacen);

        menuOperadoresFile.add(operadorMenuModificar);

        jMenuBar1.add(menuOperadoresFile);

        menuRecepcionistaFile.setText("Archivo");

        recepcionistaMenModificar.setText("Modificar");

        recepcionistaMenuCliente.setText("Cliente");
        recepcionistaMenModificar.add(recepcionistaMenuCliente);

        recepcionistaMenuEnvio.setText("Envio");
        recepcionistaMenModificar.add(recepcionistaMenuEnvio);

        menuRecepcionistaFile.add(recepcionistaMenModificar);

        jMenuBar1.add(menuRecepcionistaFile);

        sesionMenu.setText("Sesion");

        jMenuItem1.setText("Iniciar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        sesionMenu.add(jMenuItem1);

        jMenuItem2.setText("Cerrar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        sesionMenu.add(jMenuItem2);

        jMenuBar1.add(sesionMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        if (!logInFrame.isVisible()) {
            clearLogIn();
            logInFrame.setVisible(true);
        }
        System.out.println(logInFrame.isVisible());
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        signOut();
        clearLogIn();
        actual = null;
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void logInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInBtnActionPerformed
//    frameCliente.setVisible(true);
//    frameUsuario.setVisible(true);
//    connectionManager.check();
        String uName = "";
        String uPass;
        incorrectValuesLbl.setVisible(false);
        try {
            uName = logInUsrTxt.getText();
            uPass = String.copyValueOf(LogInPassTxt.getPassword());
            consulta = connectionManager.select("Usuario", "*", "Usuario = '" +uName+ "' AND Password = '" + uPass + "'");
                consulta.first();
             if (!consulta.wasNull()) {
                actual = new Usuario(consulta.getString("Nombre")
                        , consulta.getString("Usuario")
                        , consulta.getString("Password"),
                        consulta.getInt("Tipo"));
            } else {
                incorrectValuesLbl.setVisible(true);
            }
            System.out.println(actual.getNombre());
        } catch (Exception e) {
           incorrectValuesLbl.setVisible(true);
            //e.printStackTrace();
        }
        if (actual != null) {
            logInFrame.doDefaultCloseAction();
            switch (actual.getTipo()) {
                case 1:
                    menuAdministradorFile.setVisible(true);
                    menuAdministradorFile.setEnabled(true);
                    break;
                case 2:
                    menuOperadoresFile.setVisible(true);
                    menuOperadoresFile.setEnabled(true);
                    break;
                default:
                    throw new AssertionError();
            }
        }
        

//    connectionManager.select("Usuario", "Usuario", "Password = 'test'");
    }//GEN-LAST:event_logInBtnActionPerformed

    private void clientSaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientSaveBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientSaveBtnActionPerformed

    private void usrShowPassBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usrShowPassBtnActionPerformed
        
        if (usrShowPassBtn.isSelected()) {
            usrPassTxt.setEchoChar((char)0);
        } else {
            usrPassTxt.setEchoChar('*');
        }
    }//GEN-LAST:event_usrShowPassBtnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setExtendedState(this.MAXIMIZED_BOTH); 
    }//GEN-LAST:event_formWindowOpened

    private void administradorMenuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_administradorMenuUsuarioActionPerformed
        frameUsuario.setVisible(true);
    }//GEN-LAST:event_administradorMenuUsuarioActionPerformed

    private void usrSaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usrSaveBtnActionPerformed
       String table = "Usuario",
               usr = usrUsrTxt.getText(),
               pass = String.valueOf(usrPassTxt.getPassword()),
               name = usrNameTxt.getText();
       int type = usrTypeCombo.getSelectedIndex()+1;
       String values = String.format("'%s','%s','%s',%d", usr, pass, name, type);
        if (connectionManager.select(table, "Usuario", "'"+usr+"'") != null) {
            connectionManager.insert(table, values);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Nombre de usuario no disponible");
        }
    }//GEN-LAST:event_usrSaveBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
            
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField LogInPassTxt;
    private javax.swing.JMenu administradorMenuModificar;
    private javax.swing.JMenuItem administradorMenuPC;
    private javax.swing.JMenuItem administradorMenuRuta;
    private javax.swing.JMenuItem administradorMenuUsuario;
    private javax.swing.JTextField clientNameTxt;
    private javax.swing.JTextField clientNitTxt;
    private javax.swing.JButton clientSaveBtn;
    private javax.swing.JButton clientSearchBtn;
    private javax.swing.JInternalFrame frameCliente;
    private javax.swing.JInternalFrame framePaquete;
    private javax.swing.JInternalFrame frameUsuario;
    private javax.swing.JLabel incorrectValuesLbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton logInBtn;
    private javax.swing.JInternalFrame logInFrame;
    private javax.swing.JTextField logInUsrTxt;
    private javax.swing.JMenu menuAdministradorFile;
    private javax.swing.JMenu menuOperadoresFile;
    private javax.swing.JMenu menuRecepcionistaFile;
    private javax.swing.JMenuItem operadorMenuAlmacen;
    private javax.swing.JMenu operadorMenuModificar;
    private javax.swing.JTextField paqueteNitTxt;
    private javax.swing.JComboBox<String> paquetePaquetesCombo;
    private javax.swing.JFormattedTextField paquetePesoTxt;
    private javax.swing.JCheckBox paquetePriorizadoCheck;
    private javax.swing.JMenu recepcionistaMenModificar;
    private javax.swing.JMenuItem recepcionistaMenuCliente;
    private javax.swing.JMenuItem recepcionistaMenuEnvio;
    private javax.swing.JMenu sesionMenu;
    private javax.swing.JTextField usrNameTxt;
    private javax.swing.JPasswordField usrPassTxt;
    private javax.swing.JButton usrSaveBtn;
    private javax.swing.JButton usrSearchBtn;
    private javax.swing.JToggleButton usrShowPassBtn;
    private javax.swing.JComboBox<String> usrTypeCombo;
    private javax.swing.JTextField usrUsrTxt;
    // End of variables declaration//GEN-END:variables
}
